#!/usr/bin/env bash
set -eu
real_git=/usr/bin/git
subcommand=""
for arg in "$@"; do
  case "$arg" in
    -*) ;;
    *) subcommand="$arg"; break ;;
  esac
done
case "$subcommand" in
  push|fetch|pull|tag|ls-remote)
    printf 'QA_AUDIT_BLOCKED_GIT: git %s is disabled\n' "$subcommand" >&2
    exit 77
    ;;
esac
exec "$real_git" "$@"
