import json,subprocess,sys
from datetime import datetime,timezone
from pathlib import Path
def test_p22_retrieval_reranker(repo_root:Path,tmp_path:Path)->None:
 run='p22-reranker-'+datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%SZ');out=repo_root/'outputs/phase22-real-journeys'/run;out.mkdir(parents=True);rs=[]
 def add(split,q,d,rel,base,overlap,cite,auth):rs.append({'split':split,'query_id':q,'document_id':d,'provenance_id':'source:'+d,'relevance':rel,'base_score':base,'features':{'term_overlap':overlap,'citation_match':cite,'authority':auth,'freshness':.5}})
 for q in ('train-a','train-b'):add('train',q,q+'-relevant',2,.2,1,1,.9);add('train',q,q+'-noise',0,.9,.1,0,.1)
 for q in ('holdout-a','holdout-b'):add('holdout',q,q+'-relevant',2,.2,1,1,.9);add('holdout',q,q+'-noise',0,.9,.1,0,.1)
 dataset=out/'labeled-retrieval.jsonl';dataset.write_text(''.join(json.dumps(x)+'\n' for x in rs));result=out/'reranker-result.json';tool=repo_root/'harness/lib/retrieval_reranker.py';p=subprocess.run([sys.executable,str(tool),'train','--dataset',str(dataset),'--k','1','--output',str(result)],capture_output=True,text=True,timeout=30);d=json.loads(result.read_text());a={'cli_accepted':p.returncode==0 and d['status']=='accepted','trained_weights':any(abs(x)>0 for x in d['model']['weights'].values()),'recall_not_regressed':d['metrics']['recall_delta']>=0,'ndcg_improved':d['metrics']['ndcg_delta']>0,'provenance_preserved':d['metrics']['provenance_preserved'],'rollback_recorded':bool(d['promotion']['rollback'])};e={'schema_version':'phase22.retrieval_reranker.v1','journey_id':'NT-memory-retrieval','run_id':run,'repo_head':subprocess.check_output(['git','rev-parse','HEAD'],cwd=repo_root,text=True).strip(),'production_entrypoint':str(tool),'assertions':a,'result':str(result),'status':'PASS_WITH_KNOWN_LIMITATIONS' if all(a.values()) else 'FAIL','limitations':d['limitations']};(out/'journey-result.json').write_text(json.dumps(e,indent=2)+'\n');assert all(a.values()),out/'journey-result.json'
